site_name: 'TechDocs'
site_description: 'TechDocs Documentation'

plugins:
  - techdocs-core

nav:
  - Introduction: index.md
  - Creating Documentation: creating-docs.md
  - Adding your project to Backstage: adding-to-backstage.md
