site_name: 'Users and Groups'
site_description: 'Documentation for User/Group Entities in Backstage'

plugins:
  - techdocs-core

nav:
  - Introduction: index.md
  - Creating a Group: creating-groups.md
  - Creating and adding Users: users.md
