name: Notify Codeowners On Config Change
on: [push]
  jobs:
    logLatestRelease:
      runs-on: ubuntu-latest
      steps:
        - uses: octokit/request-action@v2.x
          id: get_latest_release
          with:
            route: GET /repos/{owner}/{repo}/releases/latest
            owner: department-of-veterans-affairs
            repo: lighthouse-backstage
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"